#cloud-config
users:
  - name: web
    primary_group: web
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - "ssh-ed25519 <public_ssh-key_sequence> <key_name>"

package_reboot_if_required: true
package_update: true
package_upgrade: true
packages:
  - nginx
  - nmap
